export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PUBLIC_GALLERY = 'GET_PUBLIC_GALLERY';
export const GET_PUBLIC_GALLERIES = 'GET_PUBLIC_GALLERIES';
export const ADD_PUBLIC_GALLERY = 'ADD_PUBLIC_GALLERY';